 CREATE TABLE ROLE
    (
      ID          NUMBER NOT NULL,
      NAME        VARCHAR2(200) NOT NULL,
      DESCRIPTION VARCHAR2(200) ,
      CONSTRAINT ROLE_PK PRIMARY KEY ( ID ) ENABLE
    ) ;
    
 CREATE TABLE USERTB
    (
      ID           NUMBER NOT NULL ENABLE,
      FIRSTNAME    VARCHAR2(200 BYTE) NOT NULL,
      LASTNAME     VARCHAR2(200 BYTE) NOT NULL,
      AGE          NUMBER,
      SUPERVISORID NUMBER,
      CONSTRAINT USERTB_PK PRIMARY KEY (ID) ENABLE,
      CONSTRAINT USERTB_SUPERVISORID_FK FOREIGN KEY (SUPERVISORID) REFERENCES USERTB (ID) ENABLE
    ) ;
    
 CREATE TABLE USERROLE
    (
      USERTBID NUMBER NOT NULL ENABLE,
      ROLEID NUMBER NOT NULL ENABLE,
      CONSTRAINT USERROLE_PK PRIMARY KEY (USERTBID, ROLEID),
      CONSTRAINT USERROLE_USERTB_FK FOREIGN KEY (USERTBID) REFERENCES USERTB (ID) ENABLE,
      CONSTRAINT USERROLE_ROLE_FK FOREIGN KEY (ROLEID) REFERENCES ROLE (ID) ENABLE
    ) ;
 
