 CREATE TABLE ROLE
    (
      ID          NUMBER NOT NULL,
      NAME        VARCHAR2(200) NOT NULL,
      DESCRIPTION VARCHAR2(200) ,
      CONSTRAINT ROLE_PK PRIMARY KEY ( ID ) ENABLE
    ) ;
    
 CREATE TABLE "USER"
    (
      ID           NUMBER NOT NULL ENABLE,
      FIRSTNAME    VARCHAR2(200 BYTE) NOT NULL,
      LASTNAME     VARCHAR2(200 BYTE) NOT NULL,
      AGE          NUMBER,
      SUPERVISORID NUMBER,
      CONSTRAINT USER_PK PRIMARY KEY (ID) ENABLE,
      CONSTRAINT USER_SUPERVISORID_FK FOREIGN KEY (SUPERVISORID) REFERENCES "USER" (ID) ENABLE
    ) ;
    
 CREATE TABLE USERROLE
    (
      USERID NUMBER NOT NULL ENABLE,
      ROLEID NUMBER NOT NULL ENABLE,
      CONSTRAINT USERROLE_PK PRIMARY KEY (USERID, ROLEID),
      CONSTRAINT USERROLE_USER_FK FOREIGN KEY (USERID) REFERENCES "USER" (ID) ENABLE,
      CONSTRAINT USERROLE_ROLE_FK FOREIGN KEY (ROLEID) REFERENCES "ROLE" (ID) ENABLE
    ) ;
 
